//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public int ID { get; set; }
        public string DisplayName { get; set; }
        public string icon { get; set; }
        public string type { get; set; }
        public string ordinal { get; set; }
        public string path { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
